[package]
name = "soft_control"
version = "0.1.0"
authors = ["Avnerus <avnerus@gmail.com>"]

[dependencies]
ws = "*"
serialport = "*"
argparse = "*"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
